// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.15.6
// source: gdb.proto

package model

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Rows struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EffectedRows int32 `protobuf:"varint,1,opt,name=effectedRows,proto3" json:"effectedRows,omitempty"`
}

func (x *Rows) Reset() {
	*x = Rows{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gdb_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Rows) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rows) ProtoMessage() {}

func (x *Rows) ProtoReflect() protoreflect.Message {
	mi := &file_gdb_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rows.ProtoReflect.Descriptor instead.
func (*Rows) Descriptor() ([]byte, []int) {
	return file_gdb_proto_rawDescGZIP(), []int{0}
}

func (x *Rows) GetEffectedRows() int32 {
	if x != nil {
		return x.EffectedRows
	}
	return 0
}

type Cols struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EffectedCols int32 `protobuf:"varint,1,opt,name=effectedCols,proto3" json:"effectedCols,omitempty"`
}

func (x *Cols) Reset() {
	*x = Cols{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gdb_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Cols) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cols) ProtoMessage() {}

func (x *Cols) ProtoReflect() protoreflect.Message {
	mi := &file_gdb_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cols.ProtoReflect.Descriptor instead.
func (*Cols) Descriptor() ([]byte, []int) {
	return file_gdb_proto_rawDescGZIP(), []int{1}
}

func (x *Cols) GetEffectedCols() int32 {
	if x != nil {
		return x.EffectedCols
	}
	return 0
}

type AddedGroupInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GroupName   string   `protobuf:"bytes,1,opt,name=groupName,proto3" json:"groupName,omitempty"`
	ColumnNames []string `protobuf:"bytes,2,rep,name=columnNames,proto3" json:"columnNames,omitempty"`
}

func (x *AddedGroupInfo) Reset() {
	*x = AddedGroupInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gdb_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddedGroupInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddedGroupInfo) ProtoMessage() {}

func (x *AddedGroupInfo) ProtoReflect() protoreflect.Message {
	mi := &file_gdb_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddedGroupInfo.ProtoReflect.Descriptor instead.
func (*AddedGroupInfo) Descriptor() ([]byte, []int) {
	return file_gdb_proto_rawDescGZIP(), []int{2}
}

func (x *AddedGroupInfo) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *AddedGroupInfo) GetColumnNames() []string {
	if x != nil {
		return x.ColumnNames
	}
	return nil
}

type AddedGroupInfos struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GroupInfos []*AddedGroupInfo `protobuf:"bytes,1,rep,name=groupInfos,proto3" json:"groupInfos,omitempty"`
}

func (x *AddedGroupInfos) Reset() {
	*x = AddedGroupInfos{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gdb_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddedGroupInfos) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddedGroupInfos) ProtoMessage() {}

func (x *AddedGroupInfos) ProtoReflect() protoreflect.Message {
	mi := &file_gdb_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddedGroupInfos.ProtoReflect.Descriptor instead.
func (*AddedGroupInfos) Descriptor() ([]byte, []int) {
	return file_gdb_proto_rawDescGZIP(), []int{3}
}

func (x *AddedGroupInfos) GetGroupInfos() []*AddedGroupInfo {
	if x != nil {
		return x.GroupInfos
	}
	return nil
}

type GroupNamesInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GroupNames []string `protobuf:"bytes,1,rep,name=groupNames,proto3" json:"groupNames,omitempty"`
}

func (x *GroupNamesInfo) Reset() {
	*x = GroupNamesInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gdb_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GroupNamesInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupNamesInfo) ProtoMessage() {}

func (x *GroupNamesInfo) ProtoReflect() protoreflect.Message {
	mi := &file_gdb_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupNamesInfo.ProtoReflect.Descriptor instead.
func (*GroupNamesInfo) Descriptor() ([]byte, []int) {
	return file_gdb_proto_rawDescGZIP(), []int{4}
}

func (x *GroupNamesInfo) GetGroupNames() []string {
	if x != nil {
		return x.GroupNames
	}
	return nil
}

type GroupPropertyInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ItemCount       string   `protobuf:"bytes,1,opt,name=itemCount,proto3" json:"itemCount,omitempty"`
	ItemColumnNames []string `protobuf:"bytes,2,rep,name=itemColumnNames,proto3" json:"itemColumnNames,omitempty"`
}

func (x *GroupPropertyInfo) Reset() {
	*x = GroupPropertyInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gdb_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GroupPropertyInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupPropertyInfo) ProtoMessage() {}

func (x *GroupPropertyInfo) ProtoReflect() protoreflect.Message {
	mi := &file_gdb_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupPropertyInfo.ProtoReflect.Descriptor instead.
func (*GroupPropertyInfo) Descriptor() ([]byte, []int) {
	return file_gdb_proto_rawDescGZIP(), []int{5}
}

func (x *GroupPropertyInfo) GetItemCount() string {
	if x != nil {
		return x.ItemCount
	}
	return ""
}

func (x *GroupPropertyInfo) GetItemColumnNames() []string {
	if x != nil {
		return x.ItemColumnNames
	}
	return nil
}

type QueryGroupPropertyInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GroupName string `protobuf:"bytes,1,opt,name=groupName,proto3" json:"groupName,omitempty"`
	Condition string `protobuf:"bytes,2,opt,name=condition,proto3" json:"condition,omitempty"`
}

func (x *QueryGroupPropertyInfo) Reset() {
	*x = QueryGroupPropertyInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gdb_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryGroupPropertyInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryGroupPropertyInfo) ProtoMessage() {}

func (x *QueryGroupPropertyInfo) ProtoReflect() protoreflect.Message {
	mi := &file_gdb_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryGroupPropertyInfo.ProtoReflect.Descriptor instead.
func (*QueryGroupPropertyInfo) Descriptor() ([]byte, []int) {
	return file_gdb_proto_rawDescGZIP(), []int{6}
}

func (x *QueryGroupPropertyInfo) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *QueryGroupPropertyInfo) GetCondition() string {
	if x != nil {
		return x.Condition
	}
	return ""
}

type UpdatedGroupNameInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OldGroupName string `protobuf:"bytes,1,opt,name=oldGroupName,proto3" json:"oldGroupName,omitempty"`
	NewGroupName string `protobuf:"bytes,2,opt,name=newGroupName,proto3" json:"newGroupName,omitempty"`
}

func (x *UpdatedGroupNameInfo) Reset() {
	*x = UpdatedGroupNameInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gdb_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdatedGroupNameInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatedGroupNameInfo) ProtoMessage() {}

func (x *UpdatedGroupNameInfo) ProtoReflect() protoreflect.Message {
	mi := &file_gdb_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatedGroupNameInfo.ProtoReflect.Descriptor instead.
func (*UpdatedGroupNameInfo) Descriptor() ([]byte, []int) {
	return file_gdb_proto_rawDescGZIP(), []int{7}
}

func (x *UpdatedGroupNameInfo) GetOldGroupName() string {
	if x != nil {
		return x.OldGroupName
	}
	return ""
}

func (x *UpdatedGroupNameInfo) GetNewGroupName() string {
	if x != nil {
		return x.NewGroupName
	}
	return ""
}

type UpdatedGroupNamesInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Infos []*UpdatedGroupNameInfo `protobuf:"bytes,1,rep,name=infos,proto3" json:"infos,omitempty"`
}

func (x *UpdatedGroupNamesInfo) Reset() {
	*x = UpdatedGroupNamesInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gdb_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdatedGroupNamesInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatedGroupNamesInfo) ProtoMessage() {}

func (x *UpdatedGroupNamesInfo) ProtoReflect() protoreflect.Message {
	mi := &file_gdb_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatedGroupNamesInfo.ProtoReflect.Descriptor instead.
func (*UpdatedGroupNamesInfo) Descriptor() ([]byte, []int) {
	return file_gdb_proto_rawDescGZIP(), []int{8}
}

func (x *UpdatedGroupNamesInfo) GetInfos() []*UpdatedGroupNameInfo {
	if x != nil {
		return x.Infos
	}
	return nil
}

type UpdatedGroupColumnNamesInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GroupName      string   `protobuf:"bytes,1,opt,name=groupName,proto3" json:"groupName,omitempty"`
	OldColumnNames []string `protobuf:"bytes,2,rep,name=oldColumnNames,proto3" json:"oldColumnNames,omitempty"`
	NewColumnNames []string `protobuf:"bytes,3,rep,name=newColumnNames,proto3" json:"newColumnNames,omitempty"`
}

func (x *UpdatedGroupColumnNamesInfo) Reset() {
	*x = UpdatedGroupColumnNamesInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gdb_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdatedGroupColumnNamesInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatedGroupColumnNamesInfo) ProtoMessage() {}

func (x *UpdatedGroupColumnNamesInfo) ProtoReflect() protoreflect.Message {
	mi := &file_gdb_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatedGroupColumnNamesInfo.ProtoReflect.Descriptor instead.
func (*UpdatedGroupColumnNamesInfo) Descriptor() ([]byte, []int) {
	return file_gdb_proto_rawDescGZIP(), []int{9}
}

func (x *UpdatedGroupColumnNamesInfo) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *UpdatedGroupColumnNamesInfo) GetOldColumnNames() []string {
	if x != nil {
		return x.OldColumnNames
	}
	return nil
}

func (x *UpdatedGroupColumnNamesInfo) GetNewColumnNames() []string {
	if x != nil {
		return x.NewColumnNames
	}
	return nil
}

type DeletedGroupColumnNamesInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GroupName   string   `protobuf:"bytes,1,opt,name=groupName,proto3" json:"groupName,omitempty"`
	ColumnNames []string `protobuf:"bytes,2,rep,name=columnNames,proto3" json:"columnNames,omitempty"`
}

func (x *DeletedGroupColumnNamesInfo) Reset() {
	*x = DeletedGroupColumnNamesInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gdb_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeletedGroupColumnNamesInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletedGroupColumnNamesInfo) ProtoMessage() {}

func (x *DeletedGroupColumnNamesInfo) ProtoReflect() protoreflect.Message {
	mi := &file_gdb_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletedGroupColumnNamesInfo.ProtoReflect.Descriptor instead.
func (*DeletedGroupColumnNamesInfo) Descriptor() ([]byte, []int) {
	return file_gdb_proto_rawDescGZIP(), []int{10}
}

func (x *DeletedGroupColumnNamesInfo) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *DeletedGroupColumnNamesInfo) GetColumnNames() []string {
	if x != nil {
		return x.ColumnNames
	}
	return nil
}

type AddedGroupColumnsInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GroupName     string   `protobuf:"bytes,1,opt,name=groupName,proto3" json:"groupName,omitempty"`
	ColumnNames   []string `protobuf:"bytes,2,rep,name=columnNames,proto3" json:"columnNames,omitempty"`
	DefaultValues []string `protobuf:"bytes,3,rep,name=defaultValues,proto3" json:"defaultValues,omitempty"`
}

func (x *AddedGroupColumnsInfo) Reset() {
	*x = AddedGroupColumnsInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gdb_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddedGroupColumnsInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddedGroupColumnsInfo) ProtoMessage() {}

func (x *AddedGroupColumnsInfo) ProtoReflect() protoreflect.Message {
	mi := &file_gdb_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddedGroupColumnsInfo.ProtoReflect.Descriptor instead.
func (*AddedGroupColumnsInfo) Descriptor() ([]byte, []int) {
	return file_gdb_proto_rawDescGZIP(), []int{11}
}

func (x *AddedGroupColumnsInfo) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *AddedGroupColumnsInfo) GetColumnNames() []string {
	if x != nil {
		return x.ColumnNames
	}
	return nil
}

func (x *AddedGroupColumnsInfo) GetDefaultValues() []string {
	if x != nil {
		return x.DefaultValues
	}
	return nil
}

type AddedItemsInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GroupName string     `protobuf:"bytes,1,opt,name=groupName,proto3" json:"groupName,omitempty"`
	Values    []*GdbItem `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"`
}

func (x *AddedItemsInfo) Reset() {
	*x = AddedItemsInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gdb_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddedItemsInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddedItemsInfo) ProtoMessage() {}

func (x *AddedItemsInfo) ProtoReflect() protoreflect.Message {
	mi := &file_gdb_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddedItemsInfo.ProtoReflect.Descriptor instead.
func (*AddedItemsInfo) Descriptor() ([]byte, []int) {
	return file_gdb_proto_rawDescGZIP(), []int{12}
}

func (x *AddedItemsInfo) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *AddedItemsInfo) GetValues() []*GdbItem {
	if x != nil {
		return x.Values
	}
	return nil
}

type DeletedItemsInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GroupName string `protobuf:"bytes,1,opt,name=groupName,proto3" json:"groupName,omitempty"`
	Condition string `protobuf:"bytes,2,opt,name=condition,proto3" json:"condition,omitempty"`
}

func (x *DeletedItemsInfo) Reset() {
	*x = DeletedItemsInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gdb_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeletedItemsInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletedItemsInfo) ProtoMessage() {}

func (x *DeletedItemsInfo) ProtoReflect() protoreflect.Message {
	mi := &file_gdb_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletedItemsInfo.ProtoReflect.Descriptor instead.
func (*DeletedItemsInfo) Descriptor() ([]byte, []int) {
	return file_gdb_proto_rawDescGZIP(), []int{13}
}

func (x *DeletedItemsInfo) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *DeletedItemsInfo) GetCondition() string {
	if x != nil {
		return x.Condition
	}
	return ""
}

type ItemsInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Infos       *ItemsInfoWithoutRow `protobuf:"bytes,1,opt,name=infos,proto3" json:"infos,omitempty"`
	ColumnNames string               `protobuf:"bytes,2,opt,name=columnNames,proto3" json:"columnNames,omitempty"`
	StartRow    int32                `protobuf:"varint,3,opt,name=startRow,proto3" json:"startRow,omitempty"`
	RowCount    int32                `protobuf:"varint,4,opt,name=rowCount,proto3" json:"rowCount,omitempty"`
}

func (x *ItemsInfo) Reset() {
	*x = ItemsInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gdb_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ItemsInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemsInfo) ProtoMessage() {}

func (x *ItemsInfo) ProtoReflect() protoreflect.Message {
	mi := &file_gdb_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemsInfo.ProtoReflect.Descriptor instead.
func (*ItemsInfo) Descriptor() ([]byte, []int) {
	return file_gdb_proto_rawDescGZIP(), []int{14}
}

func (x *ItemsInfo) GetInfos() *ItemsInfoWithoutRow {
	if x != nil {
		return x.Infos
	}
	return nil
}

func (x *ItemsInfo) GetColumnNames() string {
	if x != nil {
		return x.ColumnNames
	}
	return ""
}

func (x *ItemsInfo) GetStartRow() int32 {
	if x != nil {
		return x.StartRow
	}
	return 0
}

func (x *ItemsInfo) GetRowCount() int32 {
	if x != nil {
		return x.RowCount
	}
	return 0
}

type ItemsInfoWithoutRow struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GroupName string `protobuf:"bytes,1,opt,name=groupName,proto3" json:"groupName,omitempty"`
	Condition string `protobuf:"bytes,5,opt,name=condition,proto3" json:"condition,omitempty"`
	Clause    string `protobuf:"bytes,6,opt,name=clause,proto3" json:"clause,omitempty"`
}

func (x *ItemsInfoWithoutRow) Reset() {
	*x = ItemsInfoWithoutRow{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gdb_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ItemsInfoWithoutRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemsInfoWithoutRow) ProtoMessage() {}

func (x *ItemsInfoWithoutRow) ProtoReflect() protoreflect.Message {
	mi := &file_gdb_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemsInfoWithoutRow.ProtoReflect.Descriptor instead.
func (*ItemsInfoWithoutRow) Descriptor() ([]byte, []int) {
	return file_gdb_proto_rawDescGZIP(), []int{15}
}

func (x *ItemsInfoWithoutRow) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *ItemsInfoWithoutRow) GetCondition() string {
	if x != nil {
		return x.Condition
	}
	return ""
}

func (x *ItemsInfoWithoutRow) GetClause() string {
	if x != nil {
		return x.Clause
	}
	return ""
}

type GdbItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items map[string]string `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *GdbItem) Reset() {
	*x = GdbItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gdb_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GdbItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GdbItem) ProtoMessage() {}

func (x *GdbItem) ProtoReflect() protoreflect.Message {
	mi := &file_gdb_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GdbItem.ProtoReflect.Descriptor instead.
func (*GdbItem) Descriptor() ([]byte, []int) {
	return file_gdb_proto_rawDescGZIP(), []int{16}
}

func (x *GdbItem) GetItems() map[string]string {
	if x != nil {
		return x.Items
	}
	return nil
}

type GdbItems struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ItemValues []*GdbItem `protobuf:"bytes,2,rep,name=itemValues,proto3" json:"itemValues,omitempty"`
}

func (x *GdbItems) Reset() {
	*x = GdbItems{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gdb_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GdbItems) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GdbItems) ProtoMessage() {}

func (x *GdbItems) ProtoReflect() protoreflect.Message {
	mi := &file_gdb_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GdbItems.ProtoReflect.Descriptor instead.
func (*GdbItems) Descriptor() ([]byte, []int) {
	return file_gdb_proto_rawDescGZIP(), []int{17}
}

func (x *GdbItems) GetItemValues() []*GdbItem {
	if x != nil {
		return x.ItemValues
	}
	return nil
}

type GdbItemsWithCount struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ItemCount  int32      `protobuf:"varint,1,opt,name=itemCount,proto3" json:"itemCount,omitempty"`
	ItemValues []*GdbItem `protobuf:"bytes,2,rep,name=itemValues,proto3" json:"itemValues,omitempty"`
}

func (x *GdbItemsWithCount) Reset() {
	*x = GdbItemsWithCount{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gdb_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GdbItemsWithCount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GdbItemsWithCount) ProtoMessage() {}

func (x *GdbItemsWithCount) ProtoReflect() protoreflect.Message {
	mi := &file_gdb_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GdbItemsWithCount.ProtoReflect.Descriptor instead.
func (*GdbItemsWithCount) Descriptor() ([]byte, []int) {
	return file_gdb_proto_rawDescGZIP(), []int{18}
}

func (x *GdbItemsWithCount) GetItemCount() int32 {
	if x != nil {
		return x.ItemCount
	}
	return 0
}

func (x *GdbItemsWithCount) GetItemValues() []*GdbItem {
	if x != nil {
		return x.ItemValues
	}
	return nil
}

type ItemValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ItemName  string `protobuf:"bytes,1,opt,name=itemName,proto3" json:"itemName,omitempty"`
	Value     string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	TimeStamp string `protobuf:"bytes,3,opt,name=timeStamp,proto3" json:"timeStamp,omitempty"`
}

func (x *ItemValue) Reset() {
	*x = ItemValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gdb_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ItemValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemValue) ProtoMessage() {}

func (x *ItemValue) ProtoReflect() protoreflect.Message {
	mi := &file_gdb_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemValue.ProtoReflect.Descriptor instead.
func (*ItemValue) Descriptor() ([]byte, []int) {
	return file_gdb_proto_rawDescGZIP(), []int{19}
}

func (x *ItemValue) GetItemName() string {
	if x != nil {
		return x.ItemName
	}
	return ""
}

func (x *ItemValue) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *ItemValue) GetTimeStamp() string {
	if x != nil {
		return x.TimeStamp
	}
	return ""
}

type BatchWriteString struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GroupName     string       `protobuf:"bytes,1,opt,name=groupName,proto3" json:"groupName,omitempty"`
	WithTimeStamp bool         `protobuf:"varint,2,opt,name=withTimeStamp,proto3" json:"withTimeStamp,omitempty"`
	ItemValues    []*ItemValue `protobuf:"bytes,3,rep,name=itemValues,proto3" json:"itemValues,omitempty"`
}

func (x *BatchWriteString) Reset() {
	*x = BatchWriteString{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gdb_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BatchWriteString) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchWriteString) ProtoMessage() {}

func (x *BatchWriteString) ProtoReflect() protoreflect.Message {
	mi := &file_gdb_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchWriteString.ProtoReflect.Descriptor instead.
func (*BatchWriteString) Descriptor() ([]byte, []int) {
	return file_gdb_proto_rawDescGZIP(), []int{20}
}

func (x *BatchWriteString) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *BatchWriteString) GetWithTimeStamp() bool {
	if x != nil {
		return x.WithTimeStamp
	}
	return false
}

func (x *BatchWriteString) GetItemValues() []*ItemValue {
	if x != nil {
		return x.ItemValues
	}
	return nil
}

type QueryRealTimeDataString struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ItemNames []string `protobuf:"bytes,1,rep,name=itemNames,proto3" json:"itemNames,omitempty"`
}

func (x *QueryRealTimeDataString) Reset() {
	*x = QueryRealTimeDataString{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gdb_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryRealTimeDataString) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRealTimeDataString) ProtoMessage() {}

func (x *QueryRealTimeDataString) ProtoReflect() protoreflect.Message {
	mi := &file_gdb_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRealTimeDataString.ProtoReflect.Descriptor instead.
func (*QueryRealTimeDataString) Descriptor() ([]byte, []int) {
	return file_gdb_proto_rawDescGZIP(), []int{21}
}

func (x *QueryRealTimeDataString) GetItemNames() []string {
	if x != nil {
		return x.ItemNames
	}
	return nil
}

// Notes: because in rpc proto we can't define Current map type,so use string to replace
// current map, that is we use json.
type GdbRealTimeData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RealTimeData string `protobuf:"bytes,1,opt,name=realTimeData,proto3" json:"realTimeData,omitempty"`
}

func (x *GdbRealTimeData) Reset() {
	*x = GdbRealTimeData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gdb_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GdbRealTimeData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GdbRealTimeData) ProtoMessage() {}

func (x *GdbRealTimeData) ProtoReflect() protoreflect.Message {
	mi := &file_gdb_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GdbRealTimeData.ProtoReflect.Descriptor instead.
func (*GdbRealTimeData) Descriptor() ([]byte, []int) {
	return file_gdb_proto_rawDescGZIP(), []int{22}
}

func (x *GdbRealTimeData) GetRealTimeData() string {
	if x != nil {
		return x.RealTimeData
	}
	return ""
}

type QueryHistoricalDataString struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ItemNames  []string `protobuf:"bytes,1,rep,name=itemNames,proto3" json:"itemNames,omitempty"`
	StartTimes []int32  `protobuf:"varint,2,rep,packed,name=startTimes,proto3" json:"startTimes,omitempty"`
	EndTimes   []int32  `protobuf:"varint,3,rep,packed,name=endTimes,proto3" json:"endTimes,omitempty"`
	Intervals  []int32  `protobuf:"varint,4,rep,packed,name=intervals,proto3" json:"intervals,omitempty"`
}

func (x *QueryHistoricalDataString) Reset() {
	*x = QueryHistoricalDataString{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gdb_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryHistoricalDataString) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryHistoricalDataString) ProtoMessage() {}

func (x *QueryHistoricalDataString) ProtoReflect() protoreflect.Message {
	mi := &file_gdb_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryHistoricalDataString.ProtoReflect.Descriptor instead.
func (*QueryHistoricalDataString) Descriptor() ([]byte, []int) {
	return file_gdb_proto_rawDescGZIP(), []int{23}
}

func (x *QueryHistoricalDataString) GetItemNames() []string {
	if x != nil {
		return x.ItemNames
	}
	return nil
}

func (x *QueryHistoricalDataString) GetStartTimes() []int32 {
	if x != nil {
		return x.StartTimes
	}
	return nil
}

func (x *QueryHistoricalDataString) GetEndTimes() []int32 {
	if x != nil {
		return x.EndTimes
	}
	return nil
}

func (x *QueryHistoricalDataString) GetIntervals() []int32 {
	if x != nil {
		return x.Intervals
	}
	return nil
}

type GdbHistoricalData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HistoricalData string `protobuf:"bytes,1,opt,name=historicalData,proto3" json:"historicalData,omitempty"`
}

func (x *GdbHistoricalData) Reset() {
	*x = GdbHistoricalData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gdb_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GdbHistoricalData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GdbHistoricalData) ProtoMessage() {}

func (x *GdbHistoricalData) ProtoReflect() protoreflect.Message {
	mi := &file_gdb_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GdbHistoricalData.ProtoReflect.Descriptor instead.
func (*GdbHistoricalData) Descriptor() ([]byte, []int) {
	return file_gdb_proto_rawDescGZIP(), []int{24}
}

func (x *GdbHistoricalData) GetHistoricalData() string {
	if x != nil {
		return x.HistoricalData
	}
	return ""
}

type TimeStamp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TimeStamp []int32 `protobuf:"varint,1,rep,packed,name=timeStamp,proto3" json:"timeStamp,omitempty"`
}

func (x *TimeStamp) Reset() {
	*x = TimeStamp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gdb_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TimeStamp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeStamp) ProtoMessage() {}

func (x *TimeStamp) ProtoReflect() protoreflect.Message {
	mi := &file_gdb_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeStamp.ProtoReflect.Descriptor instead.
func (*TimeStamp) Descriptor() ([]byte, []int) {
	return file_gdb_proto_rawDescGZIP(), []int{25}
}

func (x *TimeStamp) GetTimeStamp() []int32 {
	if x != nil {
		return x.TimeStamp
	}
	return nil
}

type QueryHistoricalDataWithTimeStampString struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ItemNames  []string     `protobuf:"bytes,1,rep,name=itemNames,proto3" json:"itemNames,omitempty"`
	TimeStamps []*TimeStamp `protobuf:"bytes,2,rep,name=timeStamps,proto3" json:"timeStamps,omitempty"`
}

func (x *QueryHistoricalDataWithTimeStampString) Reset() {
	*x = QueryHistoricalDataWithTimeStampString{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gdb_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryHistoricalDataWithTimeStampString) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryHistoricalDataWithTimeStampString) ProtoMessage() {}

func (x *QueryHistoricalDataWithTimeStampString) ProtoReflect() protoreflect.Message {
	mi := &file_gdb_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryHistoricalDataWithTimeStampString.ProtoReflect.Descriptor instead.
func (*QueryHistoricalDataWithTimeStampString) Descriptor() ([]byte, []int) {
	return file_gdb_proto_rawDescGZIP(), []int{26}
}

func (x *QueryHistoricalDataWithTimeStampString) GetItemNames() []string {
	if x != nil {
		return x.ItemNames
	}
	return nil
}

func (x *QueryHistoricalDataWithTimeStampString) GetTimeStamps() []*TimeStamp {
	if x != nil {
		return x.TimeStamps
	}
	return nil
}

type DeadZone struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ItemName      string `protobuf:"bytes,1,opt,name=itemName,proto3" json:"itemName,omitempty"`
	DeadZoneCount int32  `protobuf:"varint,2,opt,name=deadZoneCount,proto3" json:"deadZoneCount,omitempty"`
}

func (x *DeadZone) Reset() {
	*x = DeadZone{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gdb_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeadZone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeadZone) ProtoMessage() {}

func (x *DeadZone) ProtoReflect() protoreflect.Message {
	mi := &file_gdb_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeadZone.ProtoReflect.Descriptor instead.
func (*DeadZone) Descriptor() ([]byte, []int) {
	return file_gdb_proto_rawDescGZIP(), []int{27}
}

func (x *DeadZone) GetItemName() string {
	if x != nil {
		return x.ItemName
	}
	return ""
}

func (x *DeadZone) GetDeadZoneCount() int32 {
	if x != nil {
		return x.DeadZoneCount
	}
	return 0
}

type QueryHistoricalDataWithConditionString struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ItemNames       []string     `protobuf:"bytes,1,rep,name=itemNames,proto3" json:"itemNames,omitempty"`
	TimeStamps      []*TimeStamp `protobuf:"bytes,2,rep,name=timeStamps,proto3" json:"timeStamps,omitempty"`
	StartTimes      []int32      `protobuf:"varint,3,rep,packed,name=startTimes,proto3" json:"startTimes,omitempty"`
	EndTimes        []int32      `protobuf:"varint,4,rep,packed,name=endTimes,proto3" json:"endTimes,omitempty"`
	Intervals       []int32      `protobuf:"varint,5,rep,packed,name=intervals,proto3" json:"intervals,omitempty"`
	FilterCondition string       `protobuf:"bytes,6,opt,name=filterCondition,proto3" json:"filterCondition,omitempty"`
	DeadZones       []*DeadZone  `protobuf:"bytes,7,rep,name=deadZones,proto3" json:"deadZones,omitempty"`
}

func (x *QueryHistoricalDataWithConditionString) Reset() {
	*x = QueryHistoricalDataWithConditionString{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gdb_proto_msgTypes[28]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryHistoricalDataWithConditionString) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryHistoricalDataWithConditionString) ProtoMessage() {}

func (x *QueryHistoricalDataWithConditionString) ProtoReflect() protoreflect.Message {
	mi := &file_gdb_proto_msgTypes[28]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryHistoricalDataWithConditionString.ProtoReflect.Descriptor instead.
func (*QueryHistoricalDataWithConditionString) Descriptor() ([]byte, []int) {
	return file_gdb_proto_rawDescGZIP(), []int{28}
}

func (x *QueryHistoricalDataWithConditionString) GetItemNames() []string {
	if x != nil {
		return x.ItemNames
	}
	return nil
}

func (x *QueryHistoricalDataWithConditionString) GetTimeStamps() []*TimeStamp {
	if x != nil {
		return x.TimeStamps
	}
	return nil
}

func (x *QueryHistoricalDataWithConditionString) GetStartTimes() []int32 {
	if x != nil {
		return x.StartTimes
	}
	return nil
}

func (x *QueryHistoricalDataWithConditionString) GetEndTimes() []int32 {
	if x != nil {
		return x.EndTimes
	}
	return nil
}

func (x *QueryHistoricalDataWithConditionString) GetIntervals() []int32 {
	if x != nil {
		return x.Intervals
	}
	return nil
}

func (x *QueryHistoricalDataWithConditionString) GetFilterCondition() string {
	if x != nil {
		return x.FilterCondition
	}
	return ""
}

func (x *QueryHistoricalDataWithConditionString) GetDeadZones() []*DeadZone {
	if x != nil {
		return x.DeadZones
	}
	return nil
}

type GdbInfoData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Info string `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
}

func (x *GdbInfoData) Reset() {
	*x = GdbInfoData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gdb_proto_msgTypes[29]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GdbInfoData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GdbInfoData) ProtoMessage() {}

func (x *GdbInfoData) ProtoReflect() protoreflect.Message {
	mi := &file_gdb_proto_msgTypes[29]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GdbInfoData.ProtoReflect.Descriptor instead.
func (*GdbInfoData) Descriptor() ([]byte, []int) {
	return file_gdb_proto_rawDescGZIP(), []int{29}
}

func (x *GdbInfoData) GetInfo() string {
	if x != nil {
		return x.Info
	}
	return ""
}

var File_gdb_proto protoreflect.FileDescriptor

var file_gdb_proto_rawDesc = []byte{
	0x0a, 0x09, 0x67, 0x64, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x6d, 0x6f, 0x64,
	0x65, 0x6c, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x2a, 0x0a, 0x04, 0x52, 0x6f, 0x77, 0x73, 0x12, 0x22, 0x0a, 0x0c, 0x65, 0x66, 0x66, 0x65, 0x63,
	0x74, 0x65, 0x64, 0x52, 0x6f, 0x77, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x65,
	0x66, 0x66, 0x65, 0x63, 0x74, 0x65, 0x64, 0x52, 0x6f, 0x77, 0x73, 0x22, 0x2a, 0x0a, 0x04, 0x43,
	0x6f, 0x6c, 0x73, 0x12, 0x22, 0x0a, 0x0c, 0x65, 0x66, 0x66, 0x65, 0x63, 0x74, 0x65, 0x64, 0x43,
	0x6f, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x65, 0x66, 0x66, 0x65, 0x63,
	0x74, 0x65, 0x64, 0x43, 0x6f, 0x6c, 0x73, 0x22, 0x50, 0x0a, 0x0e, 0x41, 0x64, 0x64, 0x65, 0x64,
	0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1c, 0x0a, 0x09, 0x67, 0x72, 0x6f,
	0x75, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x67, 0x72,
	0x6f, 0x75, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x6f, 0x6c, 0x75, 0x6d,
	0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x6f,
	0x6c, 0x75, 0x6d, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x22, 0x48, 0x0a, 0x0f, 0x41, 0x64, 0x64,
	0x65, 0x64, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x73, 0x12, 0x35, 0x0a, 0x0a,
	0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x15, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x41, 0x64, 0x64, 0x65, 0x64, 0x47, 0x72,
	0x6f, 0x75, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0a, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x6e,
	0x66, 0x6f, 0x73, 0x22, 0x30, 0x0a, 0x0e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4e, 0x61, 0x6d, 0x65,
	0x73, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1e, 0x0a, 0x0a, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x4e, 0x61,
	0x6d, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0a, 0x67, 0x72, 0x6f, 0x75, 0x70,
	0x4e, 0x61, 0x6d, 0x65, 0x73, 0x22, 0x5b, 0x0a, 0x11, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x50, 0x72,
	0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1c, 0x0a, 0x09, 0x69, 0x74,
	0x65, 0x6d, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x69,
	0x74, 0x65, 0x6d, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x28, 0x0a, 0x0f, 0x69, 0x74, 0x65, 0x6d,
	0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x0f, 0x69, 0x74, 0x65, 0x6d, 0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x4e, 0x61, 0x6d,
	0x65, 0x73, 0x22, 0x54, 0x0a, 0x16, 0x51, 0x75, 0x65, 0x72, 0x79, 0x47, 0x72, 0x6f, 0x75, 0x70,
	0x50, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1c, 0x0a, 0x09,
	0x67, 0x72, 0x6f, 0x75, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x6f,
	0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63,
	0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x5e, 0x0a, 0x14, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x64, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x49, 0x6e, 0x66, 0x6f,
	0x12, 0x22, 0x0a, 0x0c, 0x6f, 0x6c, 0x64, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x6f, 0x6c, 0x64, 0x47, 0x72, 0x6f, 0x75, 0x70,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x6e, 0x65, 0x77, 0x47, 0x72, 0x6f, 0x75, 0x70,
	0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x6e, 0x65, 0x77, 0x47,
	0x72, 0x6f, 0x75, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x4a, 0x0a, 0x15, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x64, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x49, 0x6e, 0x66,
	0x6f, 0x12, 0x31, 0x0a, 0x05, 0x69, 0x6e, 0x66, 0x6f, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x1b, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64,
	0x47, 0x72, 0x6f, 0x75, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05, 0x69,
	0x6e, 0x66, 0x6f, 0x73, 0x22, 0x8b, 0x01, 0x0a, 0x1b, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64,
	0x47, 0x72, 0x6f, 0x75, 0x70, 0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x73,
	0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1c, 0x0a, 0x09, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x4e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x26, 0x0a, 0x0e, 0x6f, 0x6c, 0x64, 0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x4e,
	0x61, 0x6d, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0e, 0x6f, 0x6c, 0x64, 0x43,
	0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x12, 0x26, 0x0a, 0x0e, 0x6e, 0x65,
	0x77, 0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x0e, 0x6e, 0x65, 0x77, 0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x4e, 0x61, 0x6d,
	0x65, 0x73, 0x22, 0x5d, 0x0a, 0x1b, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x47, 0x72, 0x6f,
	0x75, 0x70, 0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x49, 0x6e, 0x66,
	0x6f, 0x12, 0x1c, 0x0a, 0x09, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x20, 0x0a, 0x0b, 0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x4e, 0x61, 0x6d, 0x65,
	0x73, 0x22, 0x7d, 0x0a, 0x15, 0x41, 0x64, 0x64, 0x65, 0x64, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x43,
	0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1c, 0x0a, 0x09, 0x67, 0x72,
	0x6f, 0x75, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x67,
	0x72, 0x6f, 0x75, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x6f, 0x6c, 0x75,
	0x6d, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0b, 0x63,
	0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x12, 0x24, 0x0a, 0x0d, 0x64, 0x65,
	0x66, 0x61, 0x75, 0x6c, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x0d, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73,
	0x22, 0x56, 0x0a, 0x0e, 0x41, 0x64, 0x64, 0x65, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x49, 0x6e,
	0x66, 0x6f, 0x12, 0x1c, 0x0a, 0x09, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x26, 0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x0e, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x47, 0x64, 0x62, 0x49, 0x74, 0x65, 0x6d,
	0x52, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x22, 0x4e, 0x0a, 0x10, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1c, 0x0a, 0x09,
	0x67, 0x72, 0x6f, 0x75, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x6f,
	0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63,
	0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x97, 0x01, 0x0a, 0x09, 0x49, 0x74, 0x65,
	0x6d, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x30, 0x0a, 0x05, 0x69, 0x6e, 0x66, 0x6f, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x49, 0x74,
	0x65, 0x6d, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x57, 0x69, 0x74, 0x68, 0x6f, 0x75, 0x74, 0x52, 0x6f,
	0x77, 0x52, 0x05, 0x69, 0x6e, 0x66, 0x6f, 0x73, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x6f, 0x6c, 0x75,
	0x6d, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63,
	0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x74,
	0x61, 0x72, 0x74, 0x52, 0x6f, 0x77, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x73, 0x74,
	0x61, 0x72, 0x74, 0x52, 0x6f, 0x77, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x6f, 0x77, 0x43, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x72, 0x6f, 0x77, 0x43, 0x6f, 0x75,
	0x6e, 0x74, 0x22, 0x69, 0x0a, 0x13, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x57,
	0x69, 0x74, 0x68, 0x6f, 0x75, 0x74, 0x52, 0x6f, 0x77, 0x12, 0x1c, 0x0a, 0x09, 0x67, 0x72, 0x6f,
	0x75, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x67, 0x72,
	0x6f, 0x75, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x6f, 0x6e, 0x64, 0x69,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x6f, 0x6e, 0x64,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x6c, 0x61, 0x75, 0x73, 0x65, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x6c, 0x61, 0x75, 0x73, 0x65, 0x22, 0x74, 0x0a,
	0x07, 0x47, 0x64, 0x62, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x2f, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e,
	0x47, 0x64, 0x62, 0x49, 0x74, 0x65, 0x6d, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x1a, 0x38, 0x0a, 0x0a, 0x49, 0x74, 0x65,
	0x6d, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a,
	0x02, 0x38, 0x01, 0x22, 0x3a, 0x0a, 0x08, 0x47, 0x64, 0x62, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x12,
	0x2e, 0x0a, 0x0a, 0x69, 0x74, 0x65, 0x6d, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x47, 0x64, 0x62, 0x49,
	0x74, 0x65, 0x6d, 0x52, 0x0a, 0x69, 0x74, 0x65, 0x6d, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x22,
	0x61, 0x0a, 0x11, 0x47, 0x64, 0x62, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x57, 0x69, 0x74, 0x68, 0x43,
	0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x69, 0x74, 0x65, 0x6d, 0x43, 0x6f, 0x75, 0x6e,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x69, 0x74, 0x65, 0x6d, 0x43, 0x6f, 0x75,
	0x6e, 0x74, 0x12, 0x2e, 0x0a, 0x0a, 0x69, 0x74, 0x65, 0x6d, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x47,
	0x64, 0x62, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x0a, 0x69, 0x74, 0x65, 0x6d, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x73, 0x22, 0x5b, 0x0a, 0x09, 0x49, 0x74, 0x65, 0x6d, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12,
	0x1a, 0x0a, 0x08, 0x69, 0x74, 0x65, 0x6d, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x69, 0x74, 0x65, 0x6d, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x22,
	0x88, 0x01, 0x0a, 0x10, 0x42, 0x61, 0x74, 0x63, 0x68, 0x57, 0x72, 0x69, 0x74, 0x65, 0x53, 0x74,
	0x72, 0x69, 0x6e, 0x67, 0x12, 0x1c, 0x0a, 0x09, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x4e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x24, 0x0a, 0x0d, 0x77, 0x69, 0x74, 0x68, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x74,
	0x61, 0x6d, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0d, 0x77, 0x69, 0x74, 0x68, 0x54,
	0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x30, 0x0a, 0x0a, 0x69, 0x74, 0x65, 0x6d,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6d,
	0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x0a,
	0x69, 0x74, 0x65, 0x6d, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x22, 0x37, 0x0a, 0x17, 0x51, 0x75,
	0x65, 0x72, 0x79, 0x52, 0x65, 0x61, 0x6c, 0x54, 0x69, 0x6d, 0x65, 0x44, 0x61, 0x74, 0x61, 0x53,
	0x74, 0x72, 0x69, 0x6e, 0x67, 0x12, 0x1c, 0x0a, 0x09, 0x69, 0x74, 0x65, 0x6d, 0x4e, 0x61, 0x6d,
	0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x69, 0x74, 0x65, 0x6d, 0x4e, 0x61,
	0x6d, 0x65, 0x73, 0x22, 0x35, 0x0a, 0x0f, 0x47, 0x64, 0x62, 0x52, 0x65, 0x61, 0x6c, 0x54, 0x69,
	0x6d, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x22, 0x0a, 0x0c, 0x72, 0x65, 0x61, 0x6c, 0x54, 0x69,
	0x6d, 0x65, 0x44, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x72, 0x65,
	0x61, 0x6c, 0x54, 0x69, 0x6d, 0x65, 0x44, 0x61, 0x74, 0x61, 0x22, 0x93, 0x01, 0x0a, 0x19, 0x51,
	0x75, 0x65, 0x72, 0x79, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x69, 0x63, 0x61, 0x6c, 0x44, 0x61,
	0x74, 0x61, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x12, 0x1c, 0x0a, 0x09, 0x69, 0x74, 0x65, 0x6d,
	0x4e, 0x61, 0x6d, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x69, 0x74, 0x65,
	0x6d, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54,
	0x69, 0x6d, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x05, 0x52, 0x0a, 0x73, 0x74, 0x61, 0x72,
	0x74, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d,
	0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x05, 0x52, 0x08, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d,
	0x65, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x73, 0x18,
	0x04, 0x20, 0x03, 0x28, 0x05, 0x52, 0x09, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x73,
	0x22, 0x3b, 0x0a, 0x11, 0x47, 0x64, 0x62, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x69, 0x63, 0x61,
	0x6c, 0x44, 0x61, 0x74, 0x61, 0x12, 0x26, 0x0a, 0x0e, 0x68, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x69,
	0x63, 0x61, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x68,
	0x69, 0x73, 0x74, 0x6f, 0x72, 0x69, 0x63, 0x61, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x22, 0x29, 0x0a,
	0x09, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69,
	0x6d, 0x65, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x01, 0x20, 0x03, 0x28, 0x05, 0x52, 0x09, 0x74,
	0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x22, 0x78, 0x0a, 0x26, 0x51, 0x75, 0x65, 0x72,
	0x79, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x69, 0x63, 0x61, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x57,
	0x69, 0x74, 0x68, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x53, 0x74, 0x72, 0x69,
	0x6e, 0x67, 0x12, 0x1c, 0x0a, 0x09, 0x69, 0x74, 0x65, 0x6d, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x69, 0x74, 0x65, 0x6d, 0x4e, 0x61, 0x6d, 0x65, 0x73,
	0x12, 0x30, 0x0a, 0x0a, 0x74, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x73, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x54, 0x69, 0x6d,
	0x65, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0a, 0x74, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x6d,
	0x70, 0x73, 0x22, 0x4c, 0x0a, 0x08, 0x44, 0x65, 0x61, 0x64, 0x5a, 0x6f, 0x6e, 0x65, 0x12, 0x1a,
	0x0a, 0x08, 0x69, 0x74, 0x65, 0x6d, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x69, 0x74, 0x65, 0x6d, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x24, 0x0a, 0x0d, 0x64, 0x65,
	0x61, 0x64, 0x5a, 0x6f, 0x6e, 0x65, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0d, 0x64, 0x65, 0x61, 0x64, 0x5a, 0x6f, 0x6e, 0x65, 0x43, 0x6f, 0x75, 0x6e, 0x74,
	0x22, 0xab, 0x02, 0x0a, 0x26, 0x51, 0x75, 0x65, 0x72, 0x79, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72,
	0x69, 0x63, 0x61, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x57, 0x69, 0x74, 0x68, 0x43, 0x6f, 0x6e, 0x64,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x12, 0x1c, 0x0a, 0x09, 0x69,
	0x74, 0x65, 0x6d, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09,
	0x69, 0x74, 0x65, 0x6d, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x12, 0x30, 0x0a, 0x0a, 0x74, 0x69, 0x6d,
	0x65, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e,
	0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x52,
	0x0a, 0x74, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x73,
	0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x05, 0x52,
	0x0a, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x65,
	0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x05, 0x52, 0x08, 0x65,
	0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x69, 0x6e, 0x74, 0x65, 0x72,
	0x76, 0x61, 0x6c, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x05, 0x52, 0x09, 0x69, 0x6e, 0x74, 0x65,
	0x72, 0x76, 0x61, 0x6c, 0x73, 0x12, 0x28, 0x0a, 0x0f, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x43,
	0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f,
	0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x2d, 0x0a, 0x09, 0x64, 0x65, 0x61, 0x64, 0x5a, 0x6f, 0x6e, 0x65, 0x73, 0x18, 0x07, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x44, 0x65, 0x61, 0x64, 0x5a,
	0x6f, 0x6e, 0x65, 0x52, 0x09, 0x64, 0x65, 0x61, 0x64, 0x5a, 0x6f, 0x6e, 0x65, 0x73, 0x22, 0x21,
	0x0a, 0x0b, 0x47, 0x64, 0x62, 0x49, 0x6e, 0x66, 0x6f, 0x44, 0x61, 0x74, 0x61, 0x12, 0x12, 0x0a,
	0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x69, 0x6e, 0x66,
	0x6f, 0x32, 0x95, 0x04, 0x0a, 0x05, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x32, 0x0a, 0x09, 0x41,
	0x64, 0x64, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x12, 0x16, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c,
	0x2e, 0x41, 0x64, 0x64, 0x65, 0x64, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x73,
	0x1a, 0x0b, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x52, 0x6f, 0x77, 0x73, 0x22, 0x00, 0x12,
	0x34, 0x0a, 0x0c, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x12,
	0x15, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4e, 0x61, 0x6d,
	0x65, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x1a, 0x0b, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x52,
	0x6f, 0x77, 0x73, 0x22, 0x00, 0x12, 0x3c, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x47, 0x72, 0x6f, 0x75,
	0x70, 0x73, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x15, 0x2e, 0x6d, 0x6f, 0x64,
	0x65, 0x6c, 0x2e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x49, 0x6e, 0x66,
	0x6f, 0x22, 0x00, 0x12, 0x4d, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x50,
	0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x12, 0x1d, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e,
	0x51, 0x75, 0x65, 0x72, 0x79, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72,
	0x74, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x1a, 0x18, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x47,
	0x72, 0x6f, 0x75, 0x70, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x49, 0x6e, 0x66, 0x6f,
	0x22, 0x00, 0x12, 0x3f, 0x0a, 0x10, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x47, 0x72, 0x6f, 0x75,
	0x70, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x12, 0x1c, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x73,
	0x49, 0x6e, 0x66, 0x6f, 0x1a, 0x0b, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x52, 0x6f, 0x77,
	0x73, 0x22, 0x00, 0x12, 0x4b, 0x0a, 0x16, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x47, 0x72, 0x6f,
	0x75, 0x70, 0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x12, 0x22, 0x2e,
	0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x47, 0x72, 0x6f,
	0x75, 0x70, 0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x49, 0x6e, 0x66,
	0x6f, 0x1a, 0x0b, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x43, 0x6f, 0x6c, 0x73, 0x22, 0x00,
	0x12, 0x47, 0x0a, 0x12, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x43,
	0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x73, 0x12, 0x22, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x43, 0x6f, 0x6c, 0x75, 0x6d,
	0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x1a, 0x0b, 0x2e, 0x6d, 0x6f, 0x64,
	0x65, 0x6c, 0x2e, 0x43, 0x6f, 0x6c, 0x73, 0x22, 0x00, 0x12, 0x3e, 0x0a, 0x0f, 0x41, 0x64, 0x64,
	0x47, 0x72, 0x6f, 0x75, 0x70, 0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x73, 0x12, 0x1c, 0x2e, 0x6d,
	0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x41, 0x64, 0x64, 0x65, 0x64, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x43,
	0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x1a, 0x0b, 0x2e, 0x6d, 0x6f, 0x64,
	0x65, 0x6c, 0x2e, 0x43, 0x6f, 0x6c, 0x73, 0x22, 0x00, 0x32, 0x9d, 0x02, 0x0a, 0x04, 0x49, 0x74,
	0x65, 0x6d, 0x12, 0x30, 0x0a, 0x08, 0x41, 0x64, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x12, 0x15,
	0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x41, 0x64, 0x64, 0x65, 0x64, 0x49, 0x74, 0x65, 0x6d,
	0x73, 0x49, 0x6e, 0x66, 0x6f, 0x1a, 0x0b, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x52, 0x6f,
	0x77, 0x73, 0x22, 0x00, 0x12, 0x35, 0x0a, 0x0b, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x49, 0x74,
	0x65, 0x6d, 0x73, 0x12, 0x17, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x1a, 0x0b, 0x2e, 0x6d,
	0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x52, 0x6f, 0x77, 0x73, 0x22, 0x00, 0x12, 0x2f, 0x0a, 0x08, 0x47,
	0x65, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x12, 0x10, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e,
	0x49, 0x74, 0x65, 0x6d, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x1a, 0x0f, 0x2e, 0x6d, 0x6f, 0x64, 0x65,
	0x6c, 0x2e, 0x47, 0x64, 0x62, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x22, 0x00, 0x12, 0x41, 0x0a, 0x11,
	0x47, 0x65, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x57, 0x69, 0x74, 0x68, 0x43, 0x6f, 0x75, 0x6e,
	0x74, 0x12, 0x10, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x49,
	0x6e, 0x66, 0x6f, 0x1a, 0x18, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x47, 0x64, 0x62, 0x49,
	0x74, 0x65, 0x6d, 0x73, 0x57, 0x69, 0x74, 0x68, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x00, 0x12,
	0x38, 0x0a, 0x0b, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x12, 0x1a,
	0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x49, 0x6e, 0x66, 0x6f,
	0x57, 0x69, 0x74, 0x68, 0x6f, 0x75, 0x74, 0x52, 0x6f, 0x77, 0x1a, 0x0b, 0x2e, 0x6d, 0x6f, 0x64,
	0x65, 0x6c, 0x2e, 0x52, 0x6f, 0x77, 0x73, 0x22, 0x00, 0x32, 0x80, 0x03, 0x0a, 0x04, 0x44, 0x61,
	0x74, 0x61, 0x12, 0x34, 0x0a, 0x0a, 0x42, 0x61, 0x74, 0x63, 0x68, 0x57, 0x72, 0x69, 0x74, 0x65,
	0x12, 0x17, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x42, 0x61, 0x74, 0x63, 0x68, 0x57, 0x72,
	0x69, 0x74, 0x65, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x1a, 0x0b, 0x2e, 0x6d, 0x6f, 0x64, 0x65,
	0x6c, 0x2e, 0x52, 0x6f, 0x77, 0x73, 0x22, 0x00, 0x12, 0x4b, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x52,
	0x65, 0x61, 0x6c, 0x54, 0x69, 0x6d, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1e, 0x2e, 0x6d, 0x6f,
	0x64, 0x65, 0x6c, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x61, 0x6c, 0x54, 0x69, 0x6d,
	0x65, 0x44, 0x61, 0x74, 0x61, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x1a, 0x16, 0x2e, 0x6d, 0x6f,
	0x64, 0x65, 0x6c, 0x2e, 0x47, 0x64, 0x62, 0x52, 0x65, 0x61, 0x6c, 0x54, 0x69, 0x6d, 0x65, 0x44,
	0x61, 0x74, 0x61, 0x22, 0x00, 0x12, 0x51, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x48, 0x69, 0x73, 0x74,
	0x6f, 0x72, 0x69, 0x63, 0x61, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x12, 0x20, 0x2e, 0x6d, 0x6f, 0x64,
	0x65, 0x6c, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x69, 0x63,
	0x61, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x1a, 0x18, 0x2e, 0x6d,
	0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x47, 0x64, 0x62, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x69, 0x63,
	0x61, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x22, 0x00, 0x12, 0x67, 0x0a, 0x1a, 0x47, 0x65, 0x74, 0x48,
	0x69, 0x73, 0x74, 0x6f, 0x72, 0x69, 0x63, 0x61, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x57, 0x69, 0x74,
	0x68, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x2d, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x51,
	0x75, 0x65, 0x72, 0x79, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x69, 0x63, 0x61, 0x6c, 0x44, 0x61,
	0x74, 0x61, 0x57, 0x69, 0x74, 0x68, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x53,
	0x74, 0x72, 0x69, 0x6e, 0x67, 0x1a, 0x18, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x47, 0x64,
	0x62, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x69, 0x63, 0x61, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x22,
	0x00, 0x12, 0x39, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x44, 0x62, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x16,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x12, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x47,
	0x64, 0x62, 0x49, 0x6e, 0x66, 0x6f, 0x44, 0x61, 0x74, 0x61, 0x22, 0x00, 0x42, 0x07, 0x5a, 0x05,
	0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_gdb_proto_rawDescOnce sync.Once
	file_gdb_proto_rawDescData = file_gdb_proto_rawDesc
)

func file_gdb_proto_rawDescGZIP() []byte {
	file_gdb_proto_rawDescOnce.Do(func() {
		file_gdb_proto_rawDescData = protoimpl.X.CompressGZIP(file_gdb_proto_rawDescData)
	})
	return file_gdb_proto_rawDescData
}

var file_gdb_proto_msgTypes = make([]protoimpl.MessageInfo, 31)
var file_gdb_proto_goTypes = []interface{}{
	(*Rows)(nil),                                   // 0: model.Rows
	(*Cols)(nil),                                   // 1: model.Cols
	(*AddedGroupInfo)(nil),                         // 2: model.AddedGroupInfo
	(*AddedGroupInfos)(nil),                        // 3: model.AddedGroupInfos
	(*GroupNamesInfo)(nil),                         // 4: model.GroupNamesInfo
	(*GroupPropertyInfo)(nil),                      // 5: model.GroupPropertyInfo
	(*QueryGroupPropertyInfo)(nil),                 // 6: model.QueryGroupPropertyInfo
	(*UpdatedGroupNameInfo)(nil),                   // 7: model.UpdatedGroupNameInfo
	(*UpdatedGroupNamesInfo)(nil),                  // 8: model.UpdatedGroupNamesInfo
	(*UpdatedGroupColumnNamesInfo)(nil),            // 9: model.UpdatedGroupColumnNamesInfo
	(*DeletedGroupColumnNamesInfo)(nil),            // 10: model.DeletedGroupColumnNamesInfo
	(*AddedGroupColumnsInfo)(nil),                  // 11: model.AddedGroupColumnsInfo
	(*AddedItemsInfo)(nil),                         // 12: model.AddedItemsInfo
	(*DeletedItemsInfo)(nil),                       // 13: model.DeletedItemsInfo
	(*ItemsInfo)(nil),                              // 14: model.ItemsInfo
	(*ItemsInfoWithoutRow)(nil),                    // 15: model.ItemsInfoWithoutRow
	(*GdbItem)(nil),                                // 16: model.GdbItem
	(*GdbItems)(nil),                               // 17: model.GdbItems
	(*GdbItemsWithCount)(nil),                      // 18: model.GdbItemsWithCount
	(*ItemValue)(nil),                              // 19: model.ItemValue
	(*BatchWriteString)(nil),                       // 20: model.BatchWriteString
	(*QueryRealTimeDataString)(nil),                // 21: model.QueryRealTimeDataString
	(*GdbRealTimeData)(nil),                        // 22: model.GdbRealTimeData
	(*QueryHistoricalDataString)(nil),              // 23: model.QueryHistoricalDataString
	(*GdbHistoricalData)(nil),                      // 24: model.GdbHistoricalData
	(*TimeStamp)(nil),                              // 25: model.TimeStamp
	(*QueryHistoricalDataWithTimeStampString)(nil), // 26: model.QueryHistoricalDataWithTimeStampString
	(*DeadZone)(nil),                               // 27: model.DeadZone
	(*QueryHistoricalDataWithConditionString)(nil), // 28: model.QueryHistoricalDataWithConditionString
	(*GdbInfoData)(nil),                            // 29: model.GdbInfoData
	nil,                                            // 30: model.GdbItem.ItemsEntry
	(*emptypb.Empty)(nil),                          // 31: google.protobuf.Empty
}
var file_gdb_proto_depIdxs = []int32{
	2,  // 0: model.AddedGroupInfos.groupInfos:type_name -> model.AddedGroupInfo
	7,  // 1: model.UpdatedGroupNamesInfo.infos:type_name -> model.UpdatedGroupNameInfo
	16, // 2: model.AddedItemsInfo.values:type_name -> model.GdbItem
	15, // 3: model.ItemsInfo.infos:type_name -> model.ItemsInfoWithoutRow
	30, // 4: model.GdbItem.items:type_name -> model.GdbItem.ItemsEntry
	16, // 5: model.GdbItems.itemValues:type_name -> model.GdbItem
	16, // 6: model.GdbItemsWithCount.itemValues:type_name -> model.GdbItem
	19, // 7: model.BatchWriteString.itemValues:type_name -> model.ItemValue
	25, // 8: model.QueryHistoricalDataWithTimeStampString.timeStamps:type_name -> model.TimeStamp
	25, // 9: model.QueryHistoricalDataWithConditionString.timeStamps:type_name -> model.TimeStamp
	27, // 10: model.QueryHistoricalDataWithConditionString.deadZones:type_name -> model.DeadZone
	3,  // 11: model.Group.AddGroups:input_type -> model.AddedGroupInfos
	4,  // 12: model.Group.DeleteGroups:input_type -> model.GroupNamesInfo
	31, // 13: model.Group.GetGroups:input_type -> google.protobuf.Empty
	6,  // 14: model.Group.GetGroupProperty:input_type -> model.QueryGroupPropertyInfo
	8,  // 15: model.Group.UpdateGroupNames:input_type -> model.UpdatedGroupNamesInfo
	9,  // 16: model.Group.UpdateGroupColumnNames:input_type -> model.UpdatedGroupColumnNamesInfo
	10, // 17: model.Group.DeleteGroupColumns:input_type -> model.DeletedGroupColumnNamesInfo
	11, // 18: model.Group.AddGroupColumns:input_type -> model.AddedGroupColumnsInfo
	12, // 19: model.Item.AddItems:input_type -> model.AddedItemsInfo
	13, // 20: model.Item.DeleteItems:input_type -> model.DeletedItemsInfo
	14, // 21: model.Item.GetItems:input_type -> model.ItemsInfo
	14, // 22: model.Item.GetItemsWithCount:input_type -> model.ItemsInfo
	15, // 23: model.Item.UpdateItems:input_type -> model.ItemsInfoWithoutRow
	20, // 24: model.Data.BatchWrite:input_type -> model.BatchWriteString
	21, // 25: model.Data.GetRealTimeData:input_type -> model.QueryRealTimeDataString
	23, // 26: model.Data.GetHistoricalData:input_type -> model.QueryHistoricalDataString
	26, // 27: model.Data.GetHistoricalDataWithStamp:input_type -> model.QueryHistoricalDataWithTimeStampString
	31, // 28: model.Data.GetDbInfo:input_type -> google.protobuf.Empty
	0,  // 29: model.Group.AddGroups:output_type -> model.Rows
	0,  // 30: model.Group.DeleteGroups:output_type -> model.Rows
	4,  // 31: model.Group.GetGroups:output_type -> model.GroupNamesInfo
	5,  // 32: model.Group.GetGroupProperty:output_type -> model.GroupPropertyInfo
	0,  // 33: model.Group.UpdateGroupNames:output_type -> model.Rows
	1,  // 34: model.Group.UpdateGroupColumnNames:output_type -> model.Cols
	1,  // 35: model.Group.DeleteGroupColumns:output_type -> model.Cols
	1,  // 36: model.Group.AddGroupColumns:output_type -> model.Cols
	0,  // 37: model.Item.AddItems:output_type -> model.Rows
	0,  // 38: model.Item.DeleteItems:output_type -> model.Rows
	17, // 39: model.Item.GetItems:output_type -> model.GdbItems
	18, // 40: model.Item.GetItemsWithCount:output_type -> model.GdbItemsWithCount
	0,  // 41: model.Item.UpdateItems:output_type -> model.Rows
	0,  // 42: model.Data.BatchWrite:output_type -> model.Rows
	22, // 43: model.Data.GetRealTimeData:output_type -> model.GdbRealTimeData
	24, // 44: model.Data.GetHistoricalData:output_type -> model.GdbHistoricalData
	24, // 45: model.Data.GetHistoricalDataWithStamp:output_type -> model.GdbHistoricalData
	29, // 46: model.Data.GetDbInfo:output_type -> model.GdbInfoData
	29, // [29:47] is the sub-list for method output_type
	11, // [11:29] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_gdb_proto_init() }
func file_gdb_proto_init() {
	if File_gdb_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_gdb_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Rows); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gdb_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Cols); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gdb_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddedGroupInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gdb_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddedGroupInfos); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gdb_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GroupNamesInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gdb_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GroupPropertyInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gdb_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryGroupPropertyInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gdb_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdatedGroupNameInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gdb_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdatedGroupNamesInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gdb_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdatedGroupColumnNamesInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gdb_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeletedGroupColumnNamesInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gdb_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddedGroupColumnsInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gdb_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddedItemsInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gdb_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeletedItemsInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gdb_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ItemsInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gdb_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ItemsInfoWithoutRow); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gdb_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GdbItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gdb_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GdbItems); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gdb_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GdbItemsWithCount); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gdb_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ItemValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gdb_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BatchWriteString); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gdb_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryRealTimeDataString); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gdb_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GdbRealTimeData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gdb_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryHistoricalDataString); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gdb_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GdbHistoricalData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gdb_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TimeStamp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gdb_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryHistoricalDataWithTimeStampString); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gdb_proto_msgTypes[27].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeadZone); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gdb_proto_msgTypes[28].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryHistoricalDataWithConditionString); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gdb_proto_msgTypes[29].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GdbInfoData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_gdb_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   31,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_gdb_proto_goTypes,
		DependencyIndexes: file_gdb_proto_depIdxs,
		MessageInfos:      file_gdb_proto_msgTypes,
	}.Build()
	File_gdb_proto = out.File
	file_gdb_proto_rawDesc = nil
	file_gdb_proto_goTypes = nil
	file_gdb_proto_depIdxs = nil
}
